In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import norm
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

In [3]:
#from sklearn.cross_validation import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression

In [4]:
data = pd.read_csv('train_cleaned.csv')

In [5]:
x = data.loc[:,'2ndFlrSF_log':'SaleType_WD']

In [6]:
y = data.loc[:,'SalePrice_log':'SalePrice_log']

In [45]:
train_x, test_x, train_y, test_y= train_test_split(x,y,test_size=0.2, random_state=0)

In [7]:
x.shape

(1456, 202)

In [63]:
reg = RandomForestRegressor(n_estimators=100, max_depth=50)
reg.fit(train_x,train_y)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=50,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [64]:
reg.score(train_x,train_y)

0.9842389976055862

In [65]:
reg.get_params

<bound method BaseEstimator.get_params of RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=50,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)>

In [66]:
reg.predict(test_x).reshape((292,1))
#reg.predict(test_x)

array([[11.90058933],
       [12.28130807],
       [11.42274594],
       [11.90507017],
       [12.52787215],
       [11.78762907],
       [12.43064918],
       [12.54958522],
       [11.32747323],
       [11.76124624],
       [12.78072604],
       [12.47317322],
       [12.29089981],
       [12.48230904],
       [12.20148337],
       [12.10791601],
       [12.06700557],
       [11.75773124],
       [11.67001896],
       [12.41296158],
       [11.95917489],
       [11.64838299],
       [11.45973396],
       [11.82853824],
       [12.54167817],
       [11.69556848],
       [11.86976212],
       [11.79270348],
       [12.66952329],
       [12.34688122],
       [11.89919459],
       [11.93640394],
       [12.27529396],
       [11.86081802],
       [12.17782351],
       [11.65611855],
       [11.78141166],
       [11.73343329],
       [12.27610514],
       [11.8966661 ],
       [11.61363438],
       [11.71407857],
       [11.4480763 ],
       [12.1951771 ],
       [12.36009696],
       [11

In [67]:
np.mean((reg.predict(test_x).reshape((292,1)) - test_y)**2)

SalePrice_log    0.017187
dtype: float64

# Cross Validation

In [9]:
from sklearn.model_selection import cross_val_score
def rmse_cv(model):
    rmse= np.sqrt(-cross_val_score(model, x, y, scoring="neg_mean_squared_error", cv = 4))
    return(rmse)

In [10]:
model = RandomForestRegressor(n_estimators=100, max_depth=50)

In [11]:
rmse_cv(model).mean()

0.1372242458732552

In [12]:
model

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=50,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [68]:
data_sub = pd.read_csv('test_cleaned.csv')

In [69]:
data_sub_x = data_sub.loc[:,'2ndFlrSF_log':'SaleType_WD']

In [70]:
reg.predict(data_sub_x).reshape((1459,1))

array([[11.71975688],
       [12.0269787 ],
       [12.09610136],
       ...,
       [11.93822662],
       [11.63218723],
       [12.29443298]])

In [71]:
log_y_sub = reg.predict(data_sub_x).reshape((1459,1))

In [72]:
log_y_sub.shape

(1459, 1)

In [73]:
sub = np.exp(log_y_sub)

In [74]:
sub

array([[122977.52306201],
       [167205.47083594],
       [179171.97125597],
       ...,
       [153005.11273389],
       [112666.48019525],
       [218476.3345261 ]])

In [75]:
sub1 = pd.DataFrame(sub,columns = ['SalePrice'])

In [76]:
sub2 = pd.DataFrame(np.arange(1461,2920),columns = ['Id'])

In [77]:
sub2['SalePrice'] = sub1['SalePrice']

In [78]:
sub2.to_csv('sub_random_forest.csv',index = False)